services:

  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend:/var/www/bookify
    depends_on:
      - mysql
      - php


  php:
    build:
      context: docker
      dockerfile: php.Dockerfile
    volumes:
      - ./backend:/var/www/bookify



  mysql:
    image: mysql:8.0
    env_file:
      - env/mysql.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/www/bookify


  composer:
    build:
      context: docker
      dockerfile: composer.Dockerfile
    volumes:
      - ./backend:/var/www/bookify


  artisan:
    build:
      context: docker
      dockerfile: php.Dockerfile
    volumes:
      - ./backend:/var/www/bookify
    entrypoint: ["php", "/var/www/bookify/artisan"]

  # Node.js Service (React Frontend)
  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "5173:5173"
      volumes:
        - ./frontend:/app
        - /app/node_modules
      command: [ "npm", "run", "dev" ]
      environment:
        - CHOKIDAR_USEPOLLING=true

volumes:
  mysql_data:
