services:
  # Nginx service (serves Laravel backend)
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend:/var/www/bookify
    depends_on:
      - mysql
      - php

  # PHP Service (Laravel backend)
  php:
    build:
      context: docker
      dockerfile: php.Dockerfile
    volumes:
      - ./backend:/var/www/bookify
    command: >
      bash -c "composer create-project --prefer-dist laravel/laravel backend && php-fpm"

  # MySQL Database
  mysql:
    image: mysql:8.0
    env_file:
      - env/mysql.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/www/bookify

  # Composer Service (for Laravel dependency management)
  composer:
    build:
      context: docker
      dockerfile: composer.Dockerfile
    volumes:
      - ./backend:/var/www/bookify

  # Laravel Artisan commands
  artisan:
    build:
      context: docker
      dockerfile: php.Dockerfile
    volumes:
      - ./backend:/var/www/bookify
    entrypoint: ["php", "/var/www/bookify/artisan"]

  # Node.js Service (React Frontend)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: >
      bash -c "npx create-react-app . && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mysql_data:
